// Decompiled with JetBrains decompiler
// Type: NAudio.SoundFont.GeneratorEnum
// Assembly: NAudio, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null
// MVID: CED8B364-9D50-4A06-A0C3-526F647769F0
// Assembly location: C:\Users\admin\Desktop\EOS_Client_SP24_Version2_New\NAudio.dll

#nullable disable
namespace NAudio.SoundFont
{
  public enum GeneratorEnum
  {
    StartAddressOffset,
    EndAddressOffset,
    StartLoopAddressOffset,
    EndLoopAddressOffset,
    StartAddressCoarseOffset,
    ModulationLFOToPitch,
    VibratoLFOToPitch,
    ModulationEnvelopeToPitch,
    InitialFilterCutoffFrequency,
    InitialFilterQ,
    ModulationLFOToFilterCutoffFrequency,
    ModulationEnvelopeToFilterCutoffFrequency,
    EndAddressCoarseOffset,
    ModulationLFOToVolume,
    Unused1,
    ChorusEffectsSend,
    ReverbEffectsSend,
    Pan,
    Unused2,
    Unused3,
    Unused4,
    DelayModulationLFO,
    FrequencyModulationLFO,
    DelayVibratoLFO,
    FrequencyVibratoLFO,
    DelayModulationEnvelope,
    AttackModulationEnvelope,
    HoldModulationEnvelope,
    DecayModulationEnvelope,
    SustainModulationEnvelope,
    ReleaseModulationEnvelope,
    KeyNumberToModulationEnvelopeHold,
    KeyNumberToModulationEnvelopeDecay,
    DelayVolumeEnvelope,
    AttackVolumeEnvelope,
    HoldVolumeEnvelope,
    DecayVolumeEnvelope,
    SustainVolumeEnvelope,
    ReleaseVolumeEnvelope,
    KeyNumberToVolumeEnvelopeHold,
    KeyNumberToVolumeEnvelopeDecay,
    Instrument,
    Reserved1,
    KeyRange,
    VelocityRange,
    StartLoopAddressCoarseOffset,
    KeyNumber,
    Velocity,
    InitialAttenuation,
    Reserved2,
    EndLoopAddressCoarseOffset,
    CoarseTune,
    FineTune,
    SampleID,
    SampleModes,
    Reserved3,
    ScaleTuning,
    ExclusiveClass,
    OverridingRootKey,
    Unused5,
    UnusedEnd,
  }
}
